TFA.AddFireSound("TFA_CODWW2_TONE.Bang", {
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_00.wav",
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_01.wav", 
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_02.wav", 
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_03.wav", 
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_04.wav", 
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_05.wav", 
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_06.wav", 
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_07.wav", 
"weapons/tfa_codww2/areallybadidea/series_1/tonedeath_08.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_09.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_10.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_11.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_12.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_13.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_14.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_15.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_16.wav", 
"weapons/tfa_codww2/areallybadidea/series_2/tonedeath_17.wav"}, false,
")"
)
